services:
  - type: web
    name: customer-segmentation-dashboard
    runtime: python
    repo: https://github.com/rihhanna/customer-segmentation
    rootDir: dashboard
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0